// <auto-generated />
namespace NewsPortal.Business.Logic.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddPublishDatetoNews : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddPublishDatetoNews));
        
        string IMigrationMetadata.Id
        {
            get { return "201911182118586_Add PublishDate to News"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
